import { Injectable, OnModuleInit } from '@nestjs/common';
import { ProjectsService } from './projects.service';

@Injectable()
export class SeedService implements OnModuleInit {
  constructor(private readonly projectsService: ProjectsService) {}

  async onModuleInit() {
    console.log('Seeding projects...');
    await this.projectsService.clearAll();
    console.log('Cleared existing projects.');

    const initialProjects = [
      {
        title: 'Hub Bicycle',
        description: 'Modern brand identity and signage for an urban bicycle boutique.',
        imageUrl: '/assets/projects/hub-bicycle/Postcard-Mock-up.jpg',
        gallery: [
          '/assets/projects/hub-bicycle/Postcard-Mock-up.jpg',
          '/assets/projects/hub-bicycle/hub-mockup.jpg',
          '/assets/projects/hub-bicycle/hub_bizcard.png',
          '/assets/projects/hub-bicycle/hub-index.png',
          '/assets/projects/hub-bicycle/hub-about.png',
          '/assets/projects/hub-bicycle/hub-equipment.png',
          '/assets/projects/hub-bicycle/hub-service.png',
          '/assets/projects/hub-bicycle/hub-icons.png',
          '/assets/projects/hub-bicycle/hubbicycle_hangtag_front.jpg',
          '/assets/projects/hub-bicycle/hubbicycle_hangtag_back.jpg',
        ],
        mockupUrl: '/assets/projects/hub-bicycle/Postcard-Mock-up.jpg',
        content: 'Hub Bicycle is a community-focused bike shop specializing in urban commuting and custom builds.',
        tags: ['Branding', 'Print', 'Signage', 'Web Design'],
        type: 'web,print',
        isFeatured: true,
        order: 0,
        completedDate: 'February 2026',
      },
      {
        title: 'Farmland Consulting',
        description: 'Comprehensive brand identity and stationery design for a specialized agricultural consultancy.',
        imageUrl: '/assets/projects/farmland/FarmlandConsulting_StationaryMockup.jpg',
        gallery: [
          '/assets/projects/farmland/FarmlandConsulting_StationaryMockup.jpg',
          '/assets/projects/farmland/Farmland_Letterhead_folder.png',
          '/assets/projects/farmland/Farmland_Letterhead.png',
          '/assets/projects/farmland/FarmlandConsulting_businesscard-front.png',
          '/assets/projects/farmland/FarmlandConsulting_businesscard-back.png',
          '/assets/projects/farmland/FarmlandConsulting_envelope.png',
          '/assets/projects/farmland/business_card_mockup.jpg',
          '/assets/projects/farmland/FarmlandConsulting_seal_Final.png',
        ],
        mockupUrl: '/assets/projects/farmland/FarmlandConsulting_StationaryMockup.jpg',
        content: 'Farmland Consulting provides expert advisory services to the agricultural sector.',
        tags: ['Branding', 'Print', 'Identity'],
        type: 'print',
        order: 1,
        completedDate: 'January 2026',
      },
      {
        title: 'Pinnacle Solutions',
        description: 'High-end corporate branding and digital presence for a global technology solutions provider.',
        imageUrl: '/assets/projects/pinnacle-solutions/pinnacle-biz-card-mockup.jpg',
        gallery: [
          '/assets/projects/pinnacle-solutions/pinnacle_logo.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-biz-card-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-bizcard-mockup-back-white.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-bizcard-mockup-front-white.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-bizcard-mockup-front.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-bizcard-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-website-mockup.jpg',
        ],
        mockupUrl: '/assets/projects/pinnacle-solutions/pinnacle-website-mockup.jpg',
        content: 'Pinnacle Solutions is a leading provider of enterprise-grade technology and consulting services.',
        tags: ['Branding', 'Print', 'Graphic Design'],
        type: 'print',
        order: 2,
        completedDate: 'March 2026',
      },
      {
        title: 'Dingo Films',
        description: 'Dynamic brand identity and visual storytelling for an independent film production house.',
        imageUrl: '/assets/projects/dingo/dingocard_IG3.jpg',
        gallery: [
          '/assets/projects/dingo/dingocard_IG3.jpg',
          '/assets/projects/dingo/dingo1_glam.jpg',
          '/assets/projects/dingo/dingo5_glam.jpg',
          '/assets/projects/dingo/dingocard_IG4.jpg',
          '/assets/projects/dingo/dingo-press-badge.jpg',
          '/assets/projects/dingo/dingo-press-badge2.jpg',
          '/assets/projects/dingo/dingo-tshirt1.jpg',
          '/assets/projects/dingo/dingo-tshirt2.jpg',
          '/assets/projects/dingo/dingocard_IG.jpg',
          '/assets/projects/dingo/dingocard_IG2.jpg',
        ],
        mockupUrl: '/assets/projects/dingo/dingo1_glam.jpg',
        content: 'Dingo Films is an independent production company dedicated to bold, cinematic storytelling. The branding project focused on creating a raw, high-impact visual identity that reflects the grit and creativity of their film roster.',
        tags: ['Branding', 'Print', 'Film'],
        type: 'print',
        layout: 'grid-2',
        order: 3,
        completedDate: 'March 2026',
      },
      {
        title: 'Apparent Insurance',
        description: 'Modern digital experience and brand system for a customer-centric insurance provider.',
        imageUrl: '/assets/projects/apparent-insurance/APPARENTINSURANCE_RETRIEVE_MOCKUP.jpg',
        gallery: [
          '/assets/projects/apparent-insurance/apparent-logo.jpg',
          '/assets/projects/apparent-insurance/apparent-web-mockup.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_RETRIEVE_MOCKUP.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_About.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_AddInfo.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Coverage.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Exterior.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Purchase.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_ThankYou.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_ssn.jpg',
        ],
        mockupUrl: '/assets/projects/apparent-insurance/APPARENTINSURANCE_RETRIEVE_MOCKUP.jpg',
        content: 'Apparent Insurance focuses on providing clear, transparent, and family-oriented insurance solutions.',
        tags: ['Branding', 'UI/UX', 'Digital Identity', 'Print'],
        type: 'web,print',
        isFeatured: true,
        order: 4,
        completedDate: 'April 2026',
      },
      {
        title: 'Progressive Insurance',
        description: 'Streamlined digital quoting experience and visual systems for a leading national insurer.',
        imageUrl: '/assets/projects/progressive-insurance/1.jpg',
        gallery: [
          '/assets/projects/progressive-insurance/1.jpg',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-21_at_9.47.55_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.12.58_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.26.32_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.37.05_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.45.50_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.47.13_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.56.14_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.58.29_AM_copy.png',
        ],
        mockupUrl: '/assets/projects/progressive-insurance/1.jpg',
        content: 'Progressive Insurance required a modern, user-centric approach to their digital platforms.',
        tags: ['UI/UX Design', 'Branding', 'Digital Strategy', 'Print'],
        type: 'web,print',
        isFeatured: true,
        order: 5,
        completedDate: 'May 2026',
      },
      {
        title: 'Movement Insurance',
        description: 'Dynamic brand identity and digital interface design for a modern insurance disruptor.',
        imageUrl: '/assets/projects/movement-insurance/1.jpg',
        gallery: [
          '/assets/projects/movement-insurance/1.jpg',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_1.56.40_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.08.24_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.13.50_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.20.03_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.28.47_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.30.10_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.57.11_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.00.03_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.03.54_PM.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.06.10_PM_copy.png',
        ],
        mockupUrl: '/assets/projects/movement-insurance/1.jpg',
        content: 'Movement Insurance is built on the philosophy of constant evolution and user-centricity.',
        tags: ['Branding', 'UI/UX Design', 'Digital Identity', 'Print'],
        type: 'web,print',
        isFeatured: true,
        order: 6,
        completedDate: 'June 2026',
      },
      {
        title: 'Homesite Home Insurance',
        description: 'Cohesive brand system and digital experience for a leading home insurance provider.',
        imageUrl: '/assets/projects/homesite/1.jpg',
        gallery: [
          '/assets/projects/homesite/1.jpg',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_1.56.03_PM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.53.55_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.54.50_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.56.14_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.58.39_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.59.53_AM.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.00.41_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.01.47_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.02.58_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.05.23_AM_copy.png',
        ],
        mockupUrl: '/assets/projects/homesite/1.jpg',
        content: 'Homesite Home Insurance required a modern visual identity that emphasizes reliability and trust.',
        tags: ['Branding', 'UI/UX Design', 'Print Design'],
        type: 'web,print',
        isFeatured: true,
        order: 7,
        completedDate: 'July 2026',
      },
      {
        title: 'Electric Insurance',
        description: 'High-performance digital presence and visual overhaul for a premium insurer.',
        imageUrl: '/assets/projects/electric/1.jpg',
        gallery: [
          '/assets/projects/electric/1.jpg',
          '/assets/projects/electric/Electric-About-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-AddInfo-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Coverage-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Exterior-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Interior-Desktop_copy.jpg',
        ],
        mockupUrl: '/assets/projects/electric/1.jpg',
        content: 'Electric Insurance provides specialized personal and commercial insurance solutions.',
        tags: ['UI/UX Design', 'Branding', 'Digital Identity', 'Print'],
        type: 'web,print',
        isFeatured: true,
        order: 8,
        completedDate: 'August 2026',
      },
      {
        title: 'Sorella Home Solutions',
        description: 'Sophisticated corporate website for a premium home concierge service company.',
        imageUrl: '/assets/projects/sorella/sorella-case-study10.jpg',
        gallery: [
          '/assets/projects/sorella/sorella-case-study10.jpg',
          '/assets/projects/sorella/sorella-case-study1.jpg',
        ],
        mockupUrl: '/assets/projects/sorella/sorella-mockup.jpg',
        content: 'Developed a professional digital presence for a premium home concierge service.',
        tags: ['Web', 'UI/UX Design'],
        type: 'web',
        order: 9,
        completedDate: 'September 2025',
      },
      {
        title: 'Clinical Resources SLP Platform',
        description: 'Revolutionary digital assessment platform for speech-language pathologists.',
        imageUrl: '/assets/projects/clinical/cr-hero.jpg',
        gallery: [
          '/assets/projects/clinical/cr-hero.jpg',
          '/assets/projects/clinical/cr-main.jpg',
        ],
        mockupUrl: '/assets/projects/clinical/clinical-mockup.jpg',
        content: 'An evidence-based platform designed to empower pathologists with digital tools.',
        tags: ['Angular', 'Clinical Tech'],
        type: 'web',
        order: 10,
        completedDate: 'August 2025',
      },
      {
        title: 'SOFFRA Climbing Platform',
        description: 'Global social media platform for cyclists and mountain climbing enthusiasts.',
        imageUrl: '/assets/projects/soffra/soffra-main-hero.jpg',
        gallery: [
          '/assets/projects/soffra/soffra-main-hero.jpg',
        ],
        mockupUrl: '/assets/projects/soffra/soffra-mockup.jpg',
        content: 'A comprehensive SaaS platform focused on global mountain climbing segments.',
        tags: ['Angular', 'Node.js'],
        type: 'web',
        order: 11,
        completedDate: 'June 2022',
      },
      {
        title: 'Flourrish Environmental Funding',
        description: 'Global crowdsourcing platform for funding environmental restoration.',
        imageUrl: '/assets/projects/flourrish/flourrish-case-study9.jpg',
        gallery: [
          '/assets/projects/flourrish/flourrish-case-study9.jpg',
        ],
        mockupUrl: '/assets/projects/flourrish/flourrish-mockup.jpg',
        content: 'Flourrish is a revolutionary environmental fintech platform.',
        tags: ['Angular', 'FinTech'],
        type: 'web',
        order: 12,
        completedDate: 'October 2025',
      },
      {
        title: 'Pixlhaus Internet Technologies',
        description: 'Full-service digital agency specializing in high-performance web solutions.',
        imageUrl: '/assets/projects/pixlhaus/pixlhaus-case-study1.jpg',
        gallery: [
          '/assets/projects/pixlhaus/pixlhaus-case-study1.jpg',
        ],
        mockupUrl: '/assets/projects/pixlhaus/pixlhaus-mockup.jpg',
        content: 'Pixlhaus is a comprehensive digital agency delivering pixel-perfect websites.',
        tags: ['React', 'Angular'],
        type: 'web',
        order: 13,
        completedDate: 'July 2025',
      },
      {
        title: 'Harrison Deller Art',
        description: 'Digital home for a compulsive creator of images and subconscious manifestations.',
        imageUrl: '/assets/projects/harrison-deller-art/harrison-art-2.png',
        gallery: [
          '/assets/projects/harrison-deller-art/harrison-art-2.png',
        ],
        mockupUrl: '/assets/projects/harrison-deller-art/harrison-art-mockup.png',
        content: 'Harrison Deller is a prolific Paraguayan artist and musician.',
        tags: ['Fine Art', 'Custom CMS'],
        type: 'web',
        order: 14,
        completedDate: 'February 2026',
      },
      {
        title: 'Tour de France Mountain Climb Series',
        description: 'A stunning poster series celebrating legendary mountain climbs.',
        imageUrl: '/assets/projects/tour-de-france/tourmalet.jpg',
        gallery: [
          '/assets/projects/tour-de-france/tourmalet.jpg',
          '/assets/projects/tour-de-france/stelvio.jpg',
          '/assets/projects/tour-de-france/montventoux.jpg',
          '/assets/projects/tour-de-france/alpe_Dhuez.jpg',
          '/assets/projects/tour-de-france/aubisque.jpg',
          '/assets/projects/tour-de-france/madeleine.jpg',
          '/assets/projects/tour-de-france/flandeers.jpg',
          '/assets/projects/tour-de-france/galibier.jpg',
          '/assets/projects/tour-de-france/gavia.jpg',
          '/assets/projects/tour-de-france/parisroubaix.jpg',
        ],
        mockupUrl: '/assets/projects/tour-de-france/alpe_Dhuez.jpg',
        content: 'Limited-edition posters capturing the beauty and challenge of iconic mountain passes.',
        tags: ['Print', 'Poster Series'],
        type: 'print',
        layout: 'grid-3',
        order: 15,
        completedDate: 'February 2026',
      },
      {
        title: "Martha's Vineyard Poster Series",
        description: 'A vintage-inspired collection of maps and posters for Martha’s Vineyard.',
        imageUrl: '/assets/projects/mv/katama-airpark.jpg',
        gallery: [
          '/assets/projects/mv/katama-airpark.jpg',
          '/assets/projects/mv/aquinnah.jpg',
          '/assets/projects/mv/cape-poge.jpg',
          '/assets/projects/mv/corbin-norton.jpg',
          '/assets/projects/mv/flying-horses.jpg',
          '/assets/projects/mv/state-beach.jpg',
        ],
        mockupUrl: '/assets/projects/mv/katama-airpark.jpg',
        content: 'A comprehensive series of high-quality prints celebrating the unique geography of Martha’s Vineyard.',
        tags: ['Print', 'Graphic Design'],
        type: 'print',
        layout: 'grid-3',
        order: 16,
        completedDate: 'March 2026',
      },
      {
        title: 'New England Ski Resort Poster Series',
        description: 'Highly detailed topographic maps and posters of New England ski areas.',
        imageUrl: '/assets/projects/ski-maps/killington.png',
        gallery: [
          '/assets/projects/ski-maps/killington.png',
          '/assets/projects/ski-maps/stowe.png',
          '/assets/projects/ski-maps/jay-peak.png',
          '/assets/projects/ski-maps/berkshire-east.png',
          '/assets/projects/ski-maps/sugarbush.png',
          '/assets/projects/ski-maps/stratton.png',
          '/assets/projects/ski-maps/okemo.png',
          '/assets/projects/ski-maps/loon.png',
          '/assets/projects/ski-maps/sunday-river.png',
          '/assets/projects/ski-maps/mount-snow.png',
          '/assets/projects/ski-maps/attitash-bearpeak.png',
          '/assets/projects/ski-maps/bolton-valley.png',
          '/assets/projects/ski-maps/bretton-woods.png',
          '/assets/projects/ski-maps/bromley.png',
          '/assets/projects/ski-maps/burke.png',
          '/assets/projects/ski-maps/cannon.png',
          '/assets/projects/ski-maps/gunstock.png',
          '/assets/projects/ski-maps/mad-river-glen.png',
          '/assets/projects/ski-maps/pats-peak.png',
          '/assets/projects/ski-maps/pico.png',
          '/assets/projects/ski-maps/smuggs.png',
          '/assets/projects/ski-maps/sugarloaf.png',
          '/assets/projects/ski-maps/sunapee.png',
          '/assets/projects/ski-maps/waterville-valley.png',
          '/assets/projects/ski-maps/whiteface.png',
          '/assets/projects/ski-maps/wildcat.png',
        ],
        mockupUrl: '/assets/projects/ski-maps/killington.png',
        content: 'A series of over 26 unique maps capturing the intricate trail systems of major New England resorts.',
        tags: ['Print', 'Cartography'],
        type: 'print',
        layout: 'grid-2',
        order: 17,
        completedDate: 'May 2026',
      },
      {
        title: 'Rasputitsa Gravel Race Poster Series',
        description: 'Grit-filled, high-impact posters for the legendary Rasputitsa spring classic.',
        imageUrl: '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        gallery: [
          '/assets/projects/rasputitsa/2017RASP_Framed_Mockup.jpg',
          '/assets/projects/rasputitsa/2018rasputitsa.jpg',
          '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        ],
        mockupUrl: '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        content: 'Aggressive typography and rugged aesthetic reflecting the spirit of the riders.',
        tags: ['Print', 'Poster Design'],
        type: 'print',
        layout: 'grid-3',
        order: 18,
        completedDate: 'April 2026',
      },
      {
        title: 'The Hellhole Gravel Grind',
        description: 'Aggressive brand identity and apparel for a premiere South Carolina gravel event.',
        imageUrl: '/assets/projects/hellhole/HellHole.jpg',
        gallery: [
          '/assets/projects/hellhole/ccap_insta4.jpg',
          '/assets/projects/hellhole/HellHole.jpg',
          '/assets/projects/hellhole/HellHole_6.jpg',
          '/assets/projects/hellhole/Hellhole5_T-Shirt_Mockup_Front.jpg',
          '/assets/projects/hellhole/Number6-Tshirt-MockUp.jpg',
          '/assets/projects/hellhole/Hellhole_T-Shirt_FinalGraphic_Back.jpg',
          '/assets/projects/hellhole/Hellhole_T-Shirt_FinalGraphic_Front.jpg',
          '/assets/projects/hellhole/HellHole_6_T-Shirt_Graphic_Back.jpg',
          '/assets/projects/hellhole/HellHole_6_T-Shirt_Graphic.jpg',
        ],
        mockupUrl: '/assets/projects/hellhole/HellHole.jpg',
        content: 'A "devilish" and high-impact visual identity reflecting the difficulty of the race.',
        tags: ['Print', 'Apparel Design'],
        type: 'print',
        layout: 'stack',
        order: 19,
        completedDate: 'May 2026',
      },
      {
        title: 'Keep It Tight Cycling Team Apparel',
        description: 'High-performance technical apparel design for an elite regional cycling team.',
        imageUrl: '/assets/projects/kit/KIT-logo-seal.jpg',
        gallery: [
          '/assets/projects/kit/KIT-logo-seal.jpg',
          '/assets/projects/kit/JKIT-2025-Jersey1.png',
          '/assets/projects/kit/JKIT-2025-Jersey2.png',
          '/assets/projects/kit/JKIT-2025-Jersey3.png',
          '/assets/projects/kit/JKIT-2025-Jersey4.png',
          '/assets/projects/kit/JKIT-2025-Jersey5.png',
          '/assets/projects/kit/JKIT-2025-Jersey6.png',
          '/assets/projects/kit/JKIT-2025-Jersey7.png',
          '/assets/projects/kit/JKIT-2025-Jersey8.png',
          '/assets/projects/kit/JKIT-2025-Jersey9.png',
          '/assets/projects/kit/JKIT-2025-Jersey10.png',
          '/assets/projects/kit/JKIT-2025-Jersey11.jpg',
          '/assets/projects/kit/JKIT-2025-Jersey12.jpg',
          '/assets/projects/kit/JKIT-2025-Jersey13.jpg',
          '/assets/projects/kit/JKIT-2025-Jersey14.jpg',
          '/assets/projects/kit/KIT-2025-Jersey-Final.png',
          '/assets/projects/kit/Scene-01.jpg',
          '/assets/projects/kit/Scene-03.jpg',
        ],
        mockupUrl: '/assets/projects/kit/Scene-01.jpg',
        content: 'A comprehensive kit that balances aerodynamic performance with a modern aesthetic.',
        tags: ['Apparel Design', 'Branding'],
        type: 'print',
        layout: 'grid-2',
        order: 20,
        completedDate: 'June 2026',
      },
    ];

    for (const projectData of initialProjects) {
      await this.projectsService.create(projectData);
      console.log(`Added project: ${projectData.title} at order ${projectData.order}`);
    }
  }
}
