import { Injectable, OnModuleInit, Logger } from '@nestjs/common';
import { ProjectsService } from './projects.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AppSettings } from '../app-settings.entity';

@Injectable()
export class SeedService implements OnModuleInit {
  private readonly logger = new Logger(SeedService.name);
  constructor(
    private readonly projectsService: ProjectsService,
    @InjectRepository(AppSettings)
    private readonly settingsRepository: Repository<AppSettings>,
  ) {}

  async onModuleInit() {
    const SEEDER_VERSION = 'v161';
    this.logger.log(`FORCE SEED: v161`);
    this.logger.log(`Starting project seeding process [${SEEDER_VERSION}]...`);
    
    try {
      // Check if we already seeded this version
      const settings = await this.settingsRepository.findOneBy({ key: 'seeder_version' });
      if (settings && settings.heroTitle === SEEDER_VERSION) {
        this.logger.log(`Seeding version ${SEEDER_VERSION} already applied. Skipping.`);
        return;
      }

      console.log('SEEDER: Seeding needed. Clearing database...');
      await this.projectsService.clearAll();
      console.log('SEEDER: Database cleared.');

      const initialProjects = [
      {
        title: 'Findash',
        description: 'FINDASH — Real-Time Financial Intelligence Platform. A modern financial dashboard platform designed to transform complex operational data into clear, real-time insight.',
        imageUrl: '/assets/projects/findash/findash-web-mockup.jpg',
        gallery: [
          '/assets/projects/findash/findash-stationary-mockup.jpg',
          '/assets/projects/findash/findash-bizcard-mockup.jpg',
          '/assets/projects/findash/findash-brochure.jpg',
          '/assets/projects/findash/findash-brochure-closeup.jpg',
          '/assets/projects/findash/findash-envelope-mockup.jpg',
          '/assets/projects/findash/findash-web-mockup.jpg',
          '/assets/projects/findash/findash-logo.jpg',
        ],
        mockupUrl: '/assets/projects/findash/findash-web-mockup.jpg',
        content: 'Findash is a cutting-edge fintech company that provides advanced dashboard technology for financial institutions. The branding project focused on creating a clean, professional, and tech-forward visual identity.',
        tags: ['Branding', 'Print', 'FinTech'],
        type: 'print-only',
        layout: 'grid-2',
        order: 0,
        completedDate: 'August 2026',
      },
      {
        title: 'Pinnacle Solutions',
        description: 'High-end corporate branding and digital presence for a global technology solutions provider.',
        imageUrl: '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
        gallery: [
          '/assets/projects/pinnacle-solutions/pinnacle-stationary-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-logo-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-letterhead-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-envelope-mockup.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-biz-card-mockup.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-brochure1.jpg',
          '/assets/projects/pinnacle-solutions/pinnacle-brochure2.jpg',
        ],
        mockupUrl: '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
        content: 'Pinnacle Solutions is a leading provider of enterprise-grade technology and consulting services.',
        tags: ['Branding', 'Print', 'Graphic Design'],
        type: 'print-only',
        order: 1,
        layout: 'grid-2',
        completedDate: 'March 2026',
      },
      {
        title: 'The Service Course',
        description: 'Premium brand identity and technical apparel for a high-end cycling experience center.',
        imageUrl: '/assets/projects/the-service-course/landing-page/service-course-web-mockup.jpg',
        gallery: [
          '/assets/projects/the-service-course/landing-page/service-course-web-mockup.jpg',
          '/assets/projects/the-service-course/landing-page/service-course-desktop.jpg',
          '/assets/projects/the-service-course/landing-page/service-course-tablet.jpg',
          '/assets/projects/the-service-course/landing-page/service-course-mobile.jpg',
          '/assets/projects/the-service-course/theServiceCourse-bizcard-mockup.jpg',
          '/assets/projects/the-service-course/mockup-5.jpg',
          '/assets/projects/the-service-course/stickers.jpg',
          '/assets/projects/the-service-course/mockup-4.jpg',
          '/assets/projects/the-service-course/tag-mockup.jpg',
          '/assets/projects/the-service-course/tag.jpg',
        ],
        mockupUrl: '/assets/projects/the-service-course/landing-page/service-course-web-mockup.jpg',
        content: 'The Service Course project involved creating a sophisticated, performance-oriented visual identity that resonates with dedicated cyclists and the pursuit of professional-grade service.',
        tags: ['Branding', 'Print', 'Apparel Design'],
        type: 'print-only',
        layout: 'grid-2',
        order: 4,
        completedDate: 'February 2026',
      },
      {
        title: 'Farmland Consulting',
        description: 'Comprehensive brand identity and stationery design for a specialized agricultural consultancy.',
        imageUrl: '/assets/projects/farmland/landing page/farmland-landing-page-web-mockup.jpg',
        gallery: [
          '/assets/projects/farmland/landing page/farmland-landing-page-web-mockup.jpg',
          '/assets/projects/farmland/main_header_letterhead-mockup.jpg',
          '/assets/projects/farmland/farmland-stationary-mockup.jpg',
          '/assets/projects/farmland/envelope-mockup.jpg',
          '/assets/projects/farmland/business_card_mockup.jpg',
          '/assets/projects/farmland/FarmlandConsulting_sticker-mockup.jpg',
          '/assets/projects/farmland/FarmlandConsulting_seal_Final.png',
          '/assets/projects/farmland/FarmlandConsulting_logo.jpg',
        ],
        mockupUrl: '/assets/projects/farmland/landing page/farmland-landing-page-web-mockup.jpg',
        content: 'Farmland Consulting provides expert advisory services to the agricultural sector.',
        tags: ['Branding', 'Print', 'Identity'],
        type: 'print-only',
        order: 3,
        layout: 'grid-2',
        completedDate: 'January 2026',
      },
      {
        title: 'SOFFRA.io',
        description: 'SOFFRA is a global social platform for cyclists and runners, built around the pursuit of elevation. Through its interactive CLIMB ATLAS™ system, athletes can explore, track, and compete on thousands of uphill segments across the world.',
        imageUrl: '/assets/projects/soffra/soffra-mockup.jpg',
        gallery: [
          '/assets/projects/soffra/soffra-mockup.jpg',
          '/assets/projects/soffra/soffra-main-hero.jpg',
          '/assets/projects/soffra/climb-atlas-world.jpg',
          '/assets/projects/soffra/climb-atlas-world-list.png',
          '/assets/projects/soffra/climb-atlas-world-ranking.png',
          '/assets/projects/soffra/climb-atlas-country.png',
          '/assets/projects/soffra/climb-atlas-country-list.png',
          '/assets/projects/soffra/climb-atlas-climb-page.png',
          '/assets/projects/soffra/climb-atlas-climb-page-top.png',
          '/assets/projects/soffra/climb-atlas-climb-page-map.png',
          '/assets/projects/soffra/climb-atlas-climb-list.png',
          '/assets/projects/soffra/climb-atlas-climb-cards.png',
          '/assets/projects/soffra/climb-atlas-leader-board-topten.png',
          '/assets/projects/soffra/climb-atlas-24-forecast.png',
          '/assets/projects/soffra-brand/SOFFRA-Business-Card.jpg',
          '/assets/projects/soffra-brand/soffra-letterhead-mockup.jpg',
          '/assets/projects/soffra/soffra_flyer_mockup.jpg',
          '/assets/projects/soffra-brand/SOFFRA-jersey.jpg',
          '/assets/projects/soffra-brand/SOFFRA-leave-behind-brochure-mockup-3.jpg',
          '/assets/projects/soffra-brand/SOFFRA-leave-behind-brochure-1-mockup-1.jpg',
          '/assets/projects/soffra-brand/SOFFRA-leave-behind-brochure-2-mockup-2.jpg',
        ],
        mockupUrl: '/assets/projects/soffra/soffra-mockup.jpg',
        content: 'The SOFFRA.io branding project involved creating a cohesive and high-impact visual identity that spans across digital and physical touchpoints, including specialized cycling apparel and marketing collateral.',
        tags: ['Branding', 'Print', 'Identity'],
        type: 'print-only',
        layout: 'grid-2',
        order: 2,
        completedDate: 'March 2026',
      },
      {
        title: 'Sorella Home Solutions',
        description: 'Comprehensive brand identity and print collateral for a premium home concierge service.',
        imageUrl: '/assets/projects/sorella/sorella-mockup.jpg',
        gallery: [
          '/assets/projects/sorella/sorella-mockup.jpg',
          '/assets/projects/sorella/Landing Page/sorella-desktop.jpg',
          '/assets/projects/sorella/Landing Page/sorella-tablet.jpg',
          '/assets/projects/sorella/Landing Page/sorella-mobile.jpg',
          '/assets/projects/sorella/stationary web/sorella-stationary-mockup.jpg',
          '/assets/projects/sorella/stationary web/sorella-business-card-mockup.jpg',
          '/assets/projects/sorella/stationary web/sorella-envelope-mpckup.jpg',
          '/assets/projects/sorella/stationary web/sorella-stationary-mockup2.jpg',
        ],
        mockupUrl: '/assets/projects/sorella/sorella-mockup.jpg',
        content: 'Brand identity development and print materials for Sorella Home Solutions.',
        tags: ['Branding', 'Print', 'Identity'],
        type: 'print-only',
        layout: 'grid-2',
        order: 5,
        completedDate: 'October 2026',
      },
      {
        title: 'Clinical Resources',
        description: 'Advanced assessment platform branding and print collateral for speech-language pathologists.',
        imageUrl: '/assets/projects/clinical/clinical-mockup.jpg',
        gallery: [
          '/assets/projects/clinical/clinical-mockup.jpg',
          '/assets/projects/clinical/Landing Page/clinical-resources-desktop.jpg',
          '/assets/projects/clinical/Landing Page/clinical-resources-tablet.jpg',
          '/assets/projects/clinical/Landing Page/clinical-resources-mobile.jpg',
        ],
        mockupUrl: '/assets/projects/clinical/clinical-mockup.jpg',
        content: 'Brand identity development and specialized print materials for Clinical Resources Assessment Platform.',
        tags: ['Branding', 'Print', 'Healthcare'],
        type: 'print-only',
        layout: 'grid-2',
        order: 6,
        completedDate: 'November 2026',
      },
      {
        title: 'Flourrish Environmental Funding',
        description: 'Global crowdsourcing platform for funding environmental restoration.',
        imageUrl: '/assets/projects/flourrish/flourrish-mockup.jpg',
        gallery: [
          '/assets/projects/flourrish/flourrish-case-study1.jpg',
          '/assets/projects/flourrish/flourrish-case-study2.jpg',
          '/assets/projects/flourrish/flourrish-case-study3.jpg',
          '/assets/projects/flourrish/flourrish-case-study4.jpg',
          '/assets/projects/flourrish/flourrish-case-study5.jpg',
          '/assets/projects/flourrish/flourrish-case-study6.jpg',
          '/assets/projects/flourrish/flourrish-case-study7.jpg',
          '/assets/projects/flourrish/flourrish-case-study8.jpg',
          '/assets/projects/flourrish/flourrish-case-study9.jpg',
          '/assets/projects/flourrish/flourrish-case-study10.jpg',
        ],
        mockupUrl: '/assets/projects/flourrish/flourrish-mockup.jpg',
        content: 'Flourrish is a revolutionary environmental fintech platform.',
        tags: ['Application Development','Angular', 'FinTech'],
        type: 'print-only',
        layout: 'grid-2',
        order: 7,
        completedDate: 'October 2025',
      },
      {
        title: 'Progressive Insurance',
        description: 'Streamlined digital quoting experience and visual systems for a leading national insurer.',
        imageUrl: '/assets/projects/progressive-insurance/progressive-mockup.jpg',
        gallery: [
          '/assets/projects/progressive-insurance/progressive-mockup.jpg',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-21_at_9.47.55_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.12.58_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.26.32_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.37.05_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.45.50_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.47.13_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.56.14_AM_copy.png',
          '/assets/projects/progressive-insurance/Screen_Shot_2018-09-20_at_10.58.29_AM_copy.png',
        ],
        mockupUrl: '/assets/projects/progressive-insurance/progressive-mockup.jpg',
        content: 'Progressive Insurance required a modern, user-centric approach to their digital platforms.',
        tags: ['UI/UX Design', 'Branding', 'Digital Strategy'],
        type: 'print-only',
        isFeatured: false,
        order: 8,
        layout: 'grid-2',
        completedDate: 'May 2026',
      },

      {
        title: 'Apparent Insurance',
        description: 'Modern digital experience and brand system for a customer-centric insurance provider.',
        imageUrl: '/assets/projects/apparent-insurance/apparent-web-mockup.jpg',
        gallery: [
          '/assets/projects/apparent-insurance/apparent-web-mockup.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_RETRIEVE_MOCKUP.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_About.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_AddInfo.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Coverage.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Exterior.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_Purchase.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_ThankYou.jpg',
          '/assets/projects/apparent-insurance/APPARENTINSURANCE_HO3_ssn.jpg',
        ],
        mockupUrl: '/assets/projects/apparent-insurance/apparent-web-mockup.jpg',
        content: 'Apparent Insurance focuses on providing clear, transparent, and family-oriented insurance solutions.',
        tags: ['UX/UI Design', 'UI/UX', 'Digital Identity'],
        type: 'web',
        isFeatured: false,
        order: 10,
        layout: 'grid-2',
        completedDate: 'April 2026',
      },
      {
        title: 'Movement Insurance',
        description: 'Dynamic brand identity and digital interface design for a modern insurance disruptor.',
        imageUrl: '/assets/projects/movement-insurance/1.jpg',
        gallery: [
          '/assets/projects/movement-insurance/1.jpg',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_1.56.40_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.08.24_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.13.50_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.20.03_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.28.47_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.30.10_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_2.57.11_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.00.03_PM_copy.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.03.54_PM.png',
          '/assets/projects/movement-insurance/Screen_Shot_2018-09-14_at_3.06.10_PM_copy.png',
        ],
        mockupUrl: '/assets/projects/movement-insurance/1.jpg',
        content: 'Movement Insurance is built on the philosophy of constant evolution and user-centricity.',
        tags: ['UX/UI Design', 'UI/UX Design', 'Digital Identity'],
        type: 'web',
        isFeatured: false,
        order: 12,
        layout: 'grid-2',
        completedDate: 'June 2026',
      },
      {
        title: 'Homesite Home Insurance',
        description: 'Cohesive brand system and digital experience for a leading home insurance provider.',
        imageUrl: '/assets/projects/homesite/1.jpg',
        gallery: [
          '/assets/projects/homesite/1.jpg',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_1.56.03_PM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.53.55_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.54.50_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.56.14_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.58.39_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_10.59.53_AM.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.00.41_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.01.47_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.02.58_AM_copy.png',
          '/assets/projects/homesite/Screen_Shot_2018-09-14_at_11.05.23_AM_copy.png',
        ],
        mockupUrl: '/assets/projects/homesite/1.jpg',
        content: 'Homesite Home Insurance required a modern visual identity that emphasizes reliability and trust.',
        tags: ['UX/UI Design', 'UI/UX Design'],
        type: 'web',
        isFeatured: false,
        order: 13,
        layout: 'grid-2',
        completedDate: 'July 2026',
      },
      {
        title: 'Electric Insurance',
        description: 'High-performance digital presence and visual overhaul for a premium insurer.',
        imageUrl: '/assets/projects/electric/1.jpg',
        gallery: [
          '/assets/projects/electric/1.jpg',
          '/assets/projects/electric/Electric-About-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-AddInfo-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Coverage-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Exterior-Desktop_copy.jpg',
          '/assets/projects/electric/Electric-Interior-Desktop_copy.jpg',
        ],
        mockupUrl: '/assets/projects/electric/1.jpg',
        content: 'Electric Insurance provides specialized personal and commercial insurance solutions.',
        tags: ['UI/UX Design', 'Branding', 'Digital Identity'],
        type: 'web',
        isFeatured: false,
        order: 14,
        layout: 'grid-2',
        completedDate: 'August 2026',
      },
      {
        title: 'Elephant Insurance',
        description: 'Comprehensive digital quote-to-bind experience and brand system for a direct-to-consumer insurance provider.',
        imageUrl: '/assets/projects/elephant-insurance/elephant-insurance-web-mockup.jpg',
        gallery: [
          '/assets/projects/elephant-insurance/elephant-insurance-web-mockup.jpg',
          '/assets/projects/elephant-insurance/elephant_aboutyou.jpg',
          '/assets/projects/elephant-insurance/elephant_additionalinfo.jpg',
          '/assets/projects/elephant-insurance/elephant_coverage.jpg',
          '/assets/projects/elephant-insurance/elephant_exterior.jpg',
          '/assets/projects/elephant-insurance/elephant_interior.jpg',
          '/assets/projects/elephant-insurance/elephant_purchase.jpg',
        ],
        mockupUrl: '/assets/projects/elephant-insurance/elephant-insurance-web-mockup.jpg',
        content: 'Elephant Insurance focuses on a streamlined, user-friendly digital experience for their auto and home insurance products.',
        tags: ['UX/UI Design', 'Graphic Design', 'Insurance'],
        type: 'web',
        isFeatured: false,
        order: 15,
        layout: 'grid-2',
        completedDate: 'July 2026',
        designSpecs: [
          { label: 'Platform', value: 'Web / Responsive', type: 'technical' },
          { label: 'Role', value: 'Lead Product Designer', type: 'technical' },
          { label: 'Deliverables', value: 'UX Architecture, UI Design, Brand Identity', type: 'technical' },
        ],
      },
      {
        title: 'Sorella Home Solutions',
        description: 'Sophisticated corporate website for a premium home concierge service company.',
        imageUrl: '/assets/projects/sorella/sorella-mockup.jpg',
        gallery: [
          '/assets/projects/sorella/sorella-case-study10.jpg',
          '/assets/projects/sorella/sorella-case-study1.jpg',
          '/assets/projects/sorella/sorella-case-study2.jpg',
          '/assets/projects/sorella/sorella-case-study3.jpg',
          '/assets/projects/sorella/sorella-case-study4.jpg',
          '/assets/projects/sorella/sorella-case-study5.jpg',
          '/assets/projects/sorella/sorella-case-study6.jpg',
          '/assets/projects/sorella/sorella-case-study7.jpg',
          '/assets/projects/sorella/sorella-case-study8.jpg',
          '/assets/projects/sorella/sorella-case-study9.jpg',
        ],
        mockupUrl: '/assets/projects/sorella/sorella-mockup.jpg',
        content: 'Developed a professional digital presence for a premium home concierge service.',
        tags: ['Application Development', 'UI/UX Design'],
        type: 'web',
        isFeatured: true,
        order: 0,
        completedDate: 'September 2025',
      },
      {
        title: 'Clinical Resources SLP Platform',
        description: 'Revolutionary digital assessment platform for speech-language pathologists.',
        imageUrl: '/assets/projects/clinical/clinical-mockup.jpg',
        gallery: [
          '/assets/projects/clinical/cr-hero.jpg',
          '/assets/projects/clinical/cr-main.jpg',
          '/assets/projects/clinical/clinical-case-study1.jpg',
          '/assets/projects/clinical/clinical-case-study2.jpg',
          '/assets/projects/clinical/clinical-case-study3.jpg',
          '/assets/projects/clinical/clinical-case-study4.jpg',
          '/assets/projects/clinical/clinical-case-study5.jpg',
          '/assets/projects/clinical/clinical-case-study6.jpg',
          '/assets/projects/clinical/clinical-case-study7.jpg',
          '/assets/projects/clinical/clinical-case-study8.jpg',
          '/assets/projects/clinical/clinical-case-study9.jpg',
          '/assets/projects/clinical/clinical-case-study10.jpg',
          '/assets/projects/clinical/clinical-case-study11.jpg',
          '/assets/projects/clinical/clinical-case-study12.jpg',
          '/assets/projects/clinical/clinical-case-study13.jpg',
          '/assets/projects/clinical/clinical-case-study14.jpg',
          '/assets/projects/clinical/clinical-case-study15.jpg'
        ],
        mockupUrl: '/assets/projects/clinical/clinical-mockup.jpg',
        content: 'An evidence-based platform designed to empower pathologists with digital tools.',
        tags: ['Application Development', 'Angular', 'Clinical Tech'],
        type: 'web',
        isFeatured: true,
        order: 1,
        completedDate: 'August 2025',
      },
      {
        title: 'SOFFRA Climbing Platform',
        description: 'Global social media platform for cyclists and mountain climbing enthusiasts.',
        imageUrl: '/assets/projects/soffra/soffra-mockup.jpg',
        gallery: [
          '/assets/projects/soffra/soffra-main-hero.jpg',
          '/assets/projects/soffra/climb-atlas-24-forecast.png',
          '/assets/projects/soffra/climb-atlas-climb-cards-perspective.png',
          '/assets/projects/soffra/climb-atlas-climb-cards.png',
          '/assets/projects/soffra/climb-atlas-climb-list.png',
          '/assets/projects/soffra/climb-atlas-climb-page-map-perspective.png',
          '/assets/projects/soffra/climb-atlas-climb-page-map.png',
          '/assets/projects/soffra/climb-atlas-climb-page-top-perspective.png',
          '/assets/projects/soffra/climb-atlas-climb-page-top.png',
          '/assets/projects/soffra/climb-atlas-climb-page.png',
          '/assets/projects/soffra/soffra-mockup.jpg',
          '/assets/projects/soffra/climb-atlas-country-list.png',
          '/assets/projects/soffra/climb-atlas-country.png',
          '/assets/projects/soffra/climb-atlas-leader-board-perspective.png',
          '/assets/projects/soffra/climb-atlas-leader-board-topten.png',
          '/assets/projects/soffra/climb-atlas-weather-api-perspective.png',
          '/assets/projects/soffra/climb-atlas-weather-api.png',
          '/assets/projects/soffra/climb-atlas-world-list.png',
          '/assets/projects/soffra/climb-atlas-world-rank-list-perspective.png',
          '/assets/projects/soffra/climb-atlas-world-rank-list.png',
          '/assets/projects/soffra/climb-atlas-world-ranking.png',
          '/assets/projects/soffra/climb-atlas-world.png',
        ],
        mockupUrl: '/assets/projects/soffra/soffra-mockup.jpg',
        content: 'A comprehensive SaaS platform focused on global mountain climbing segments.',
        tags: ['Application Development','Angular', 'Node.js'],
        type: 'web',
        isFeatured: true,
        order: 2,
        completedDate: 'June 2022',
      },
      {
        title: 'Pixlhaus Internet Technologies',
        description: 'Full-service digital agency specializing in high-performance web solutions.',
        imageUrl: '/assets/projects/pixlhaus/pixlhaus-mockup.jpg',
        gallery: [
          '/assets/projects/pixlhaus/pixlhaus-case-study1.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study2.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study3.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study4.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study5.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study6.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study7.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study8.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study9.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study10.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study11.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study12.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study13.jpg',
          '/assets/projects/pixlhaus/pixlhaus-case-study14.jpg',
        ],
        mockupUrl: '/assets/projects/pixlhaus/pixlhaus-mockup.jpg',
        content: 'Pixlhaus is a comprehensive digital agency delivering pixel-perfect websites.',
        tags: ['Application Development','React', 'Angular'],
        type: 'web',
        order: 4,
        completedDate: 'July 2025',
      },
      {
        title: 'Harrison Deller Art',
        description: 'Digital home for a compulsive creator of images and subconscious manifestations.',
        imageUrl: '/assets/projects/harrison-deller-art/harrison-art-mockup.png',
        gallery: [
          '/assets/projects/harrison-deller-art/harrison-art-1.png',
          '/assets/projects/harrison-deller-art/harrison-art-2.png',
          '/assets/projects/harrison-deller-art/harrison-art-3.png',
          '/assets/projects/harrison-deller-art/harrison-art-4.png',
          '/assets/projects/harrison-deller-art/harrison-art-5.png',
          '/assets/projects/harrison-deller-art/harrison-art-6.png',
          '/assets/projects/harrison-deller-art/harrison-art-7.png',
          '/assets/projects/harrison-deller-art/harrison-art-8.png',
          '/assets/projects/harrison-deller-art/harrison-art-9.png',
        ],
        mockupUrl: '/assets/projects/harrison-deller-art/harrison-art-mockup.png',
        content: 'Harrison Deller is a prolific Paraguayan artist and musician.',
        tags: ['Application Development', 'Fine Art', 'Custom CMS'],
        type: 'web',
        order: 5,
        completedDate: 'February 2026',
      },
      {
        title: 'Pinnacle Solutions Web Site',
        description: 'Sophisticated enterprise web presence for a global technology provider.',
        imageUrl: '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
        gallery: [
          '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-index-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-services-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-services-page2.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-about-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-clients-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-clients-page2.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-client-benefits-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-human-capital-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-human-capital-page2.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-blog-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-blog-page2.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-white-papers-page2.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-contact-page.jpg',
          '/assets/projects/pinnacle-solutions-web/pinnacle-contact-page2.jpg',
        ],
        mockupUrl: '/assets/projects/pinnacle-solutions-web/pinnacle-web-mockup.jpg',
        content: 'A comprehensive web platform designed to showcase high-end corporate solutions and technology services.',
        tags: ['Application Development', 'UI/UX Design', 'Development'],
        type: 'web',
        order: 7,
        completedDate: 'March 2026',
      },
      {
        title: 'Tour de France Mountain Climb Series',
        description: 'A stunning poster series celebrating legendary mountain climbs.',
        imageUrl: '/assets/projects/tour-de-france/tourmalet.jpg',
        gallery: [
          '/assets/projects/tour-de-france/tourmalet.jpg',
          '/assets/projects/tour-de-france/stelvio.jpg',
          '/assets/projects/tour-de-france/montventoux.jpg',
          '/assets/projects/tour-de-france/alpe_Dhuez.jpg',
          '/assets/projects/tour-de-france/aubisque.jpg',
          '/assets/projects/tour-de-france/madeleine.jpg',
          '/assets/projects/tour-de-france/flandeers.jpg',
          '/assets/projects/tour-de-france/galibier.jpg',
          '/assets/projects/tour-de-france/gavia.jpg',
          '/assets/projects/tour-de-france/parisroubaix.jpg',
        ],
        mockupUrl: '/assets/projects/tour-de-france/alpe_Dhuez.jpg',
        content: 'Limited-edition posters capturing the beauty and challenge of iconic mountain passes.',
        tags: ['Print', 'Poster Series'],
        type: 'print-only',
        layout: 'grid-3',
        order: 15,
        completedDate: 'February 2026',
      },
      {
        title: "Martha's Vineyard Poster Series",
        description: 'A vintage-inspired collection of maps and posters for Martha’s Vineyard.',
        imageUrl: '/assets/projects/mv/katama-airpark.jpg',
        gallery: [
          '/assets/projects/mv/katama-airpark.jpg',
          '/assets/projects/mv/aquinnah.jpg',
          '/assets/projects/mv/cape-poge.jpg',
          '/assets/projects/mv/corbin-norton.jpg',
          '/assets/projects/mv/flying-horses.jpg',
          '/assets/projects/mv/state-beach.jpg',
        ],
        mockupUrl: '/assets/projects/mv/katama-airpark.jpg',
        content: 'A comprehensive series of high-quality prints celebrating the unique geography of Martha’s Vineyard.',
        tags: ['Print', 'Graphic Design'],
        type: 'print-only',
        layout: 'grid-3',
        order: 16,
        completedDate: 'March 2026',
      },
      {
        title: 'New England Ski Resort Poster Series',
        description: 'Highly detailed topographic maps and posters of New England ski areas.',
        imageUrl: '/assets/projects/ski-maps/killington.png',
        gallery: [
          '/assets/projects/ski-maps/killington.png',
          '/assets/projects/ski-maps/stowe.png',
          '/assets/projects/ski-maps/jay-peak.png',
          '/assets/projects/ski-maps/berkshire-east.png',
          '/assets/projects/ski-maps/sugarbush.png',
          '/assets/projects/ski-maps/stratton.png',
          '/assets/projects/ski-maps/okemo.png',
          '/assets/projects/ski-maps/loon.png',
          '/assets/projects/ski-maps/sunday-river.png',
          '/assets/projects/ski-maps/mount-snow.png',
          '/assets/projects/ski-maps/attitash-bearpeak.png',
          '/assets/projects/ski-maps/bolton-valley.png',
          '/assets/projects/ski-maps/bretton-woods.png',
          '/assets/projects/ski-maps/bromley.png',
          '/assets/projects/ski-maps/burke.png',
          '/assets/projects/ski-maps/cannon.png',
          '/assets/projects/ski-maps/gunstock.png',
          '/assets/projects/ski-maps/mad-river-glen.png',
          '/assets/projects/ski-maps/pats-peak.png',
          '/assets/projects/ski-maps/pico.png',
          '/assets/projects/ski-maps/smuggs.png',
          '/assets/projects/ski-maps/sugarloaf.png',
          '/assets/projects/ski-maps/sunapee.png',
          '/assets/projects/ski-maps/waterville-valley.png',
          '/assets/projects/ski-maps/whiteface.png',
          '/assets/projects/ski-maps/wildcat.png',
        ],
        mockupUrl: '/assets/projects/ski-maps/killington.png',
        content: 'A series of over 26 unique maps capturing the intricate trail systems of major New England resorts.',
        tags: ['Print', 'Cartography'],
        type: 'print-only',
        layout: 'grid-2',
        order: 17,
        completedDate: 'May 2026',
      },
      {
        title: 'Rasputitsa Gravel Race Poster Series',
        description: 'Grit-filled, high-impact posters for the legendary Rasputitsa spring classic.',
        imageUrl: '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        gallery: [
          '/assets/projects/rasputitsa/2017RASP_Framed_Mockup.jpg',
          '/assets/projects/rasputitsa/2018rasputitsa.jpg',
          '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        ],
        mockupUrl: '/assets/projects/rasputitsa/2019rasputitsa.jpg',
        content: 'Aggressive typography and rugged aesthetic reflecting the spirit of the riders.',
        tags: ['Print', 'Poster Design'],
        type: 'print-only',
        layout: 'grid-3',
        order: 18,
        completedDate: 'April 2026',
      },
      {
        title: 'The Hellhole Gravel Grind',
        description: 'Aggressive brand identity and apparel for a premiere South Carolina gravel event.',
        imageUrl: '/assets/projects/hellhole/HellHole.jpg',
        gallery: [
          '/assets/projects/hellhole/ccap_insta4.jpg',
          '/assets/projects/hellhole/HellHole.jpg',
          '/assets/projects/hellhole/Hellhole5_T-Shirt_Mockup_Front.jpg',
          '/assets/projects/hellhole/Number6-Tshirt-MockUp.jpg',
          '/assets/projects/hellhole/HellHole-no6.jpg',
          '/assets/projects/hellhole/Hellhole_T-Shirt_FinalGraphic_Back.jpg',
          '/assets/projects/hellhole/Hellhole_T-Shirt_FinalGraphic_Front.jpg',
          '/assets/projects/hellhole/HellHole_6_T-Shirt_Graphic_Back.jpg',
          '/assets/projects/hellhole/HellHole_6_T-Shirt_Graphic.jpg',
        ],
        mockupUrl: '/assets/projects/hellhole/HellHole.jpg',
        content: 'A "devilish" and high-impact visual identity reflecting the difficulty of the race.',
        tags: ['Print', 'Apparel Design'],
        type: 'print-only',
        layout: 'grid-2',
        order: 19,
        completedDate: 'May 2026',
      },

    ];

    for (const projectData of initialProjects) {
      try {
        const created = await this.projectsService.create(projectData);
        this.logger.log(`Added project: ${created.title} (ID: ${created.id}, Type: ${created.type}, Order: ${created.order})`);
      } catch (e) {
        this.logger.error(`Failed to add project ${projectData.title}:`, e);
      }
    }
    
    // Save seeder version to prevent re-seeding
    try {
      let settings = await this.settingsRepository.findOneBy({ key: 'seeder_version' });
      if (!settings) {
        settings = this.settingsRepository.create({ key: 'seeder_version' });
      }
      settings.heroTitle = SEEDER_VERSION;
      await this.settingsRepository.save(settings);
      this.logger.log(`Project seeding completed successfully. Version ${SEEDER_VERSION} saved.`);
    } catch (e) {
      this.logger.error('Failed to save seeder version:', e);
    }
    } catch (error) {
      this.logger.error('Failed to seed projects:', error);
    }
  }
}
